- name: Fetch confd
  become: yes
  become_user: root
  get_url:
    url: 'https://github.com/kelseyhightower/confd/releases/download/v0.16.0/confd-0.16.0-linux-amd64'
    dest: '/bin/confd'
    checksum: 'sha256:255d2559f3824dd64df059bdc533fd6b697c070db603c76aaf8d1d5e6b0cc334'
    mode: 0755

