---
- include_tasks: tasks/apt.yml
  vars:
    apt_packages:
      - apt-transport-https
      - build-essential
      - ca-certificates
      - curl
      - git
      - groff
      - jq
      - make
      - nfs-client
      - pkg-config
      - software-properties-common
      - unzip
      - wget
      - zip
- include_tasks: tasks/pip.yml
  vars:
    pip_packages:
      - awscli
- include_tasks: tasks/root.yml
- include_tasks: tasks/user.yml
- include_tasks: tasks/confd.yml

- include_tasks: tasks/only-ami.yml
  when: packer_build_name == "ami"
