- name: Copy systemd service file for AMI
  template:
    src: templates/app.service
    dest: /etc/systemd/system/app.service
    owner: root
    group: root
- name: Enable app systemd service
  systemd:
    name: app.service
    state: started
    enabled: yes

