---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: False
    #login_cmd_template: 'docker exec -ti {instance} bash'
    ansible_connection_options:
      ansible_connection: local
platforms:
  - name: localhost
provisioner:
  name: ansible
  options:
    vvv: True
    extra-vars: |
      packer_build_name=docker
      packer_builder_type=docker
      packer_http_addr=
      created=byMolecule
      image=focal
      aws_region=us-east-1
verifier:
  name: ansible
